# Generated by Django 4.2.5 on 2023-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TextToImageDjango", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="texttoimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="texttoimage",
            name="query",
            field=models.CharField(default="Def", max_length=255),
        ),
    ]
